--
-- PaperSorter Database Schema
-- Generated by dump-sql-schema.py
--
-- This schema includes:
-- - pgvector extension for embeddings
-- - All tables, sequences, and constraints
-- - All indexes for performance
-- - Custom types (preferences_source enum)
--

-- Create extension if not exists (required for vector type)
CREATE EXTENSION IF NOT EXISTS vector;

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-0ubuntu0.25.04.1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-0ubuntu0.25.04.1)

-- Started on 2025-08-02 00:10:27 KST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3777 (class 1262 OID 16386)
-- Name: papersorter; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE papersorter WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF-8';


\connect papersorter

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16387)
-- Name: papersorter; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA papersorter;


--
-- TOC entry 983 (class 1247 OID 16717)
-- Name: preferences_source; Type: TYPE; Schema: papersorter; Owner: -
--

CREATE TYPE papersorter.preferences_source AS ENUM (
    'feed-star',
    'interactive',
    'alert-feedback'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16723)
-- Name: broadcasts; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.broadcasts (
    feed_id bigint NOT NULL,
    channel_id integer NOT NULL,
    broadcasted_time timestamp with time zone
);


--
-- TOC entry 220 (class 1259 OID 16726)
-- Name: channels; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.channels (
    id integer NOT NULL,
    name text,
    endpoint_url text,
    score_threshold double precision,
    model_id integer,
    is_active boolean DEFAULT true NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 16732)
-- Name: channels_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.channels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3778 (class 0 OID 0)
-- Dependencies: 221
-- Name: channels_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.channels_id_seq OWNED BY papersorter.channels.id;


--
-- TOC entry 222 (class 1259 OID 16733)
-- Name: embeddings; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.embeddings (
    feed_id bigint NOT NULL,
    embedding public.vector(3072)
);


--
-- TOC entry 223 (class 1259 OID 16738)
-- Name: events; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.events (
    id integer NOT NULL,
    occurred timestamp with time zone DEFAULT now() NOT NULL,
    event_type text,
    external_id text,
    content text,
    feed_id bigint,
    user_id integer
);


--
-- TOC entry 224 (class 1259 OID 16744)
-- Name: events_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3779 (class 0 OID 0)
-- Dependencies: 224
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.events_id_seq OWNED BY papersorter.events.id;


--
-- TOC entry 225 (class 1259 OID 16745)
-- Name: feeds; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.feeds (
    id bigint NOT NULL,
    external_id text,
    title text NOT NULL,
    content text,
    author text,
    origin text,
    link text,
    mediaurl text,
    tldr text,
    published timestamp with time zone NOT NULL,
    added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 16751)
-- Name: feeds_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.feeds_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3780 (class 0 OID 0)
-- Dependencies: 226
-- Name: feeds_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.feeds_id_seq OWNED BY papersorter.feeds.id;


--
-- TOC entry 227 (class 1259 OID 16752)
-- Name: labeling_sessions; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.labeling_sessions (
    id bigint NOT NULL,
    feed_id bigint NOT NULL,
    user_id bigint NOT NULL,
    score double precision,
    update_time timestamp with time zone
);


--
-- TOC entry 228 (class 1259 OID 16755)
-- Name: models; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.models (
    id integer NOT NULL,
    user_id bigint,
    name text,
    created timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 16762)
-- Name: models_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.models_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3781 (class 0 OID 0)
-- Dependencies: 229
-- Name: models_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.models_id_seq OWNED BY papersorter.models.id;


--
-- TOC entry 230 (class 1259 OID 16763)
-- Name: predicted_preferences; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.predicted_preferences (
    feed_id bigint NOT NULL,
    model_id integer NOT NULL,
    score double precision NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 16766)
-- Name: preferences; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.preferences (
    id bigint NOT NULL,
    feed_id integer NOT NULL,
    user_id bigint NOT NULL,
    "time" timestamp with time zone,
    score double precision,
    source papersorter.preferences_source NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 16769)
-- Name: preferences_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.preferences_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3782 (class 0 OID 0)
-- Dependencies: 232
-- Name: preferences_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.preferences_id_seq OWNED BY papersorter.preferences.id;


--
-- TOC entry 233 (class 1259 OID 16770)
-- Name: users; Type: TABLE; Schema: papersorter; Owner: -
--

CREATE TABLE papersorter.users (
    id bigint NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    created timestamp with time zone,
    lastlogin timestamp with time zone,
    is_admin boolean DEFAULT false NOT NULL,
    timezone text DEFAULT 'Asia/Seoul'::text,
    bookmark bigint,
    feedlist_minscore integer DEFAULT 25
);


--
-- TOC entry 234 (class 1259 OID 16778)
-- Name: users_id_seq; Type: SEQUENCE; Schema: papersorter; Owner: -
--

CREATE SEQUENCE papersorter.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3783 (class 0 OID 0)
-- Dependencies: 234
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: papersorter; Owner: -
--

ALTER SEQUENCE papersorter.users_id_seq OWNED BY papersorter.users.id;


--
-- TOC entry 3557 (class 2604 OID 16779)
-- Name: channels id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.channels ALTER COLUMN id SET DEFAULT nextval('papersorter.channels_id_seq'::regclass);


--
-- TOC entry 3559 (class 2604 OID 16780)
-- Name: events id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.events ALTER COLUMN id SET DEFAULT nextval('papersorter.events_id_seq'::regclass);


--
-- TOC entry 3561 (class 2604 OID 16781)
-- Name: feeds id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.feeds ALTER COLUMN id SET DEFAULT nextval('papersorter.feeds_id_seq'::regclass);


--
-- TOC entry 3563 (class 2604 OID 16782)
-- Name: models id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.models ALTER COLUMN id SET DEFAULT nextval('papersorter.models_id_seq'::regclass);


--
-- TOC entry 3566 (class 2604 OID 16783)
-- Name: preferences id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.preferences ALTER COLUMN id SET DEFAULT nextval('papersorter.preferences_id_seq'::regclass);


--
-- TOC entry 3567 (class 2604 OID 16784)
-- Name: users id; Type: DEFAULT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.users ALTER COLUMN id SET DEFAULT nextval('papersorter.users_id_seq'::regclass);


--
-- TOC entry 3572 (class 2606 OID 16786)
-- Name: broadcasts broadcast_logs_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.broadcasts
    ADD CONSTRAINT broadcast_logs_pkey PRIMARY KEY (feed_id, channel_id);


--
-- TOC entry 3575 (class 2606 OID 16788)
-- Name: channels channels_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.channels
    ADD CONSTRAINT channels_pkey PRIMARY KEY (id);


--
-- TOC entry 3577 (class 2606 OID 16790)
-- Name: embeddings embeddings_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.embeddings
    ADD CONSTRAINT embeddings_pkey PRIMARY KEY (feed_id);


--
-- TOC entry 3579 (class 2606 OID 16792)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 3584 (class 2606 OID 16794)
-- Name: feeds feeds_external_id_unique; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.feeds
    ADD CONSTRAINT feeds_external_id_unique UNIQUE (external_id);


--
-- TOC entry 3587 (class 2606 OID 16796)
-- Name: feeds idx_16500_primary; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.feeds
    ADD CONSTRAINT idx_16500_primary PRIMARY KEY (id);


--
-- TOC entry 3594 (class 2606 OID 16798)
-- Name: labeling_sessions idx_16506_primary; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.labeling_sessions
    ADD CONSTRAINT idx_16506_primary PRIMARY KEY (id);


--
-- TOC entry 3606 (class 2606 OID 16800)
-- Name: preferences idx_16512_primary; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.preferences
    ADD CONSTRAINT idx_16512_primary PRIMARY KEY (id);


--
-- TOC entry 3598 (class 2606 OID 16802)
-- Name: models idx_models_id_unique; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.models
    ADD CONSTRAINT idx_models_id_unique UNIQUE (id);


--
-- TOC entry 3601 (class 2606 OID 16804)
-- Name: models models_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- TOC entry 3603 (class 2606 OID 16806)
-- Name: predicted_preferences predicted_preferences_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.predicted_preferences
    ADD CONSTRAINT predicted_preferences_pkey PRIMARY KEY (feed_id, model_id);


--
-- TOC entry 3611 (class 2606 OID 16808)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3613 (class 2606 OID 16810)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 3585 (class 1259 OID 16811)
-- Name: idx_16500_idx_feeds_id; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_16500_idx_feeds_id ON papersorter.feeds USING btree (external_id);


--
-- TOC entry 3604 (class 1259 OID 16812)
-- Name: idx_16512_idx_ratings_feedid; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_16512_idx_ratings_feedid ON papersorter.preferences USING btree (feed_id);


--
-- TOC entry 3573 (class 1259 OID 16813)
-- Name: idx_broadcast_logs_time; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_broadcast_logs_time ON papersorter.broadcasts USING btree (broadcasted_time);


--
-- TOC entry 3580 (class 1259 OID 16814)
-- Name: idx_events_feed; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_events_feed ON papersorter.events USING btree (feed_id);


--
-- TOC entry 3581 (class 1259 OID 16815)
-- Name: idx_events_occurred; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_events_occurred ON papersorter.events USING btree (occurred);


--
-- TOC entry 3582 (class 1259 OID 16816)
-- Name: idx_events_type; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_events_type ON papersorter.events USING btree (event_type);


--
-- TOC entry 3588 (class 1259 OID 16817)
-- Name: idx_feeds_added; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_feeds_added ON papersorter.feeds USING btree (added);


--
-- TOC entry 3589 (class 1259 OID 16818)
-- Name: idx_feeds_link; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_feeds_link ON papersorter.feeds USING btree (link);


--
-- TOC entry 3590 (class 1259 OID 16819)
-- Name: idx_feeds_mediaurl; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_feeds_mediaurl ON papersorter.feeds USING btree (mediaurl);


--
-- TOC entry 3591 (class 1259 OID 16820)
-- Name: idx_feeds_published; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_feeds_published ON papersorter.feeds USING btree (published);


--
-- TOC entry 3592 (class 1259 OID 16821)
-- Name: idx_feeds_title; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_feeds_title ON papersorter.feeds USING btree (title);


--
-- TOC entry 3595 (class 1259 OID 16822)
-- Name: idx_labeling_session; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_labeling_session ON papersorter.labeling_sessions USING btree (user_id);


--
-- TOC entry 3596 (class 1259 OID 16823)
-- Name: idx_labeling_sessions_score; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_labeling_sessions_score ON papersorter.labeling_sessions USING btree (user_id, score);


--
-- TOC entry 3599 (class 1259 OID 16824)
-- Name: idx_models_user; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_models_user ON papersorter.models USING btree (user_id);


--
-- TOC entry 3607 (class 1259 OID 16825)
-- Name: idx_preferences_score; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_preferences_score ON papersorter.preferences USING btree (score);


--
-- TOC entry 3608 (class 1259 OID 16826)
-- Name: idx_preferences_time; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_preferences_time ON papersorter.preferences USING btree ("time");


--
-- TOC entry 3609 (class 1259 OID 16827)
-- Name: idx_user_id; Type: INDEX; Schema: papersorter; Owner: -
--

CREATE INDEX idx_user_id ON papersorter.preferences USING btree (user_id);


--
-- TOC entry 3614 (class 2606 OID 16828)
-- Name: broadcasts fk_broadcast_logs_channel; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.broadcasts
    ADD CONSTRAINT fk_broadcast_logs_channel FOREIGN KEY (channel_id) REFERENCES papersorter.channels(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3615 (class 2606 OID 16833)
-- Name: broadcasts fk_broadcast_logs_feed; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.broadcasts
    ADD CONSTRAINT fk_broadcast_logs_feed FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3616 (class 2606 OID 16838)
-- Name: channels fk_channels_model; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.channels
    ADD CONSTRAINT fk_channels_model FOREIGN KEY (model_id) REFERENCES papersorter.models(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3618 (class 2606 OID 16843)
-- Name: events fk_events_feed; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.events
    ADD CONSTRAINT fk_events_feed FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3619 (class 2606 OID 66297)
-- Name: events fk_events_user; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.events
    ADD CONSTRAINT fk_events_user FOREIGN KEY (user_id) REFERENCES papersorter.users(id) ON UPDATE CASCADE;


--
-- TOC entry 3617 (class 2606 OID 16848)
-- Name: embeddings fk_feed_id; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.embeddings
    ADD CONSTRAINT fk_feed_id FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3620 (class 2606 OID 16853)
-- Name: labeling_sessions fk_labeling_sessions_feed_id; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.labeling_sessions
    ADD CONSTRAINT fk_labeling_sessions_feed_id FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3621 (class 2606 OID 16858)
-- Name: labeling_sessions fk_labeling_sessions_user_id; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.labeling_sessions
    ADD CONSTRAINT fk_labeling_sessions_user_id FOREIGN KEY (user_id) REFERENCES papersorter.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3622 (class 2606 OID 16863)
-- Name: models fk_models_user_id; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.models
    ADD CONSTRAINT fk_models_user_id FOREIGN KEY (user_id) REFERENCES papersorter.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3623 (class 2606 OID 16868)
-- Name: predicted_preferences fk_pred_pref_feed; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.predicted_preferences
    ADD CONSTRAINT fk_pred_pref_feed FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3624 (class 2606 OID 16873)
-- Name: predicted_preferences fk_pred_pref_model; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.predicted_preferences
    ADD CONSTRAINT fk_pred_pref_model FOREIGN KEY (model_id) REFERENCES papersorter.models(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3625 (class 2606 OID 16878)
-- Name: preferences fk_preferences_user_id; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.preferences
    ADD CONSTRAINT fk_preferences_user_id FOREIGN KEY (user_id) REFERENCES papersorter.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 3626 (class 2606 OID 16883)
-- Name: preferences fk_ratings_feedid; Type: FK CONSTRAINT; Schema: papersorter; Owner: -
--

ALTER TABLE ONLY papersorter.preferences
    ADD CONSTRAINT fk_ratings_feedid FOREIGN KEY (feed_id) REFERENCES papersorter.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2025-08-02 00:10:27 KST

--
-- PostgreSQL database dump complete
--


