# PaperSorter Configuration Template for Docker
# This file should be mounted as /app/config.yml in the container
# Environment variables are expanded when needed

admin_users:
  # Auto-promoted admin users (comma-separated in env var)
  # ${ADMIN_USERS}

db:
  type: postgres
  host: postgres  # Docker service name
  database: ${POSTGRES_DB:-papersorter}
  user: ${POSTGRES_USER:-papersorter}
  password: ${POSTGRES_PASSWORD:-changeme}

web:
  site_name: ${SITE_NAME:-PaperSorter}
  base_url: ${BASE_URL:-http://localhost}
  flask_secret_key: ${FLASK_SECRET_KEY}
  default_timezone: ${DEFAULT_TIMEZONE:-UTC}
  default_date_format: ${DEFAULT_DATE_FORMAT:-MMM D, YYYY}

oauth:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  github:
    client_id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
  orcid:
    client_id: ${ORCID_CLIENT_ID}
    secret: ${ORCID_CLIENT_SECRET}
    sandbox: false

embedding_api:
  api_key: ${EMBEDDING_API_KEY}
  api_url: ${EMBEDDING_API_URL:-https://api.openai.com/v1}
  model: ${EMBEDDING_MODEL:-text-embedding-3-large}
  dimensions: ${EMBEDDING_DIMENSIONS}

models:
  path: /data/models

storage:
  ai_poster_dir: /data/posters

summarization_api:
  api_key: ${SUMMARIZATION_API_KEY}
  api_url: ${SUMMARIZATION_API_URL:-https://generativelanguage.googleapis.com/v1beta/openai}
  model: ${SUMMARIZATION_MODEL:-gemini-2.0-flash-thinking-exp-01-21}

scholarly_database:
  provider: ${SCHOLARLY_PROVIDER:-semantic_scholar}
  match_date_tolerance_days: ${MATCH_DATE_TOLERANCE_DAYS:-60}
  semantic_scholar:
    api_key: ${SEMANTIC_SCHOLAR_API_KEY}
    max_retries: ${SEMANTIC_SCHOLAR_MAX_RETRIES:-5}
    retry_backoff_base: ${SEMANTIC_SCHOLAR_RETRY_BACKOFF_BASE:-2}
    throttle: ${SEMANTIC_SCHOLAR_THROTTLE:-1}
  openalex:
    email: ${OPENALEX_EMAIL}
    max_retries: ${OPENALEX_MAX_RETRIES:-5}
    retry_backoff_base: ${OPENALEX_RETRY_BACKOFF_BASE:-2}
    throttle: ${OPENALEX_THROTTLE:-0.1}

smtp:
  provider: ${SMTP_PROVIDER:-custom}
  host: ${SMTP_HOST}
  port: ${SMTP_PORT:-587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  encryption: ${SMTP_ENCRYPTION:-tls}
  timeout: ${SMTP_TIMEOUT:-30}

email:
  from_address: ${EMAIL_FROM:-papersorter@example.com}
  from_name: ${EMAIL_FROM_NAME:-PaperSorter Newsletter}
  subject_template: ${EMAIL_SUBJECT_TEMPLATE:-Research Papers Digest - {date:%Y-%m-%d}}