# PaperSorter Example Configuration File
# Copy this file to your preferred location and update with your credentials
# Default location: ./config.yml

# Database configuration
db:
  type: postgres
  host: localhost
  port: 5432
  user: papersorter
  database: papersorter
  password: "your_database_password_here"

# Google OAuth configuration for web interface
google_oauth:
  client_id: "your_google_oauth_client_id.apps.googleusercontent.com"
  secret: "your_google_oauth_client_secret"
  flask_secret_key: "generate_with_python_secrets.token_hex(32)"

# Embedding API configuration
# Supports OpenAI-compatible APIs (OpenAI, Solar LLM, Google Vertex AI via Gemini, etc.)
embedding_api:
  api_key: "your_api_key"
  # Optional: custom API endpoint (defaults to https://api.openai.com/v1)
  api_url: "https://api.openai.com/v1"
  # Optional: model name (defaults to text-embedding-3-large)
  model: "text-embedding-3-large"
  # Embedding dimensions
  dimensions: 3072

# Summarization API configuration
# Used for generating article summaries
summarization_api:
  api_key: "your_openai_api_key"
  # Optional: custom API endpoint (defaults to https://api.openai.com/v1)
  api_url: "https://api.openai.com/v1"
  # Optional: model name for summarization
  model: "gpt-4o-mini"

# Scholarly database configuration
# Choose between Semantic Scholar and OpenAlex for enriching article metadata
scholarly_database:
  # Provider to use: "semantic_scholar" or "openalex"
  provider: "semantic_scholar"
  
  # Semantic Scholar configuration (if provider is semantic_scholar)
  semantic_scholar:
    api_key: "your_semanticscholar_api_key"
    # Optional: custom API URL
    # api_url: "https://api.semanticscholar.org/graph/v1/paper"
    # Optional: throttle between requests in seconds (default: 1)
    # throttle: 1
  
  # OpenAlex configuration (if provider is openalex)
  openalex:
    # OpenAlex requires a VALID email address for polite access (no API key needed)
    # Note: test@example.com and similar fake emails will NOT work
    email: "your_real_email@domain.com"
    # Optional: custom API URL
    # api_url: "https://api.openalex.org"
    # Optional: throttle between requests in seconds (default: 0.1)
    # throttle: 0.1

# Web interface configuration
web:
  # Base URL for web interface (used for "More Like This" links in Slack)
  base_url: "https://your-domain.example.com"

# Storage configuration
storage:
  # Directory for storing AI-generated poster images
  ai_poster_dir: "./ai_posters"

# Note: Slack webhook URLs are configured per channel in the database
# Use the web interface or direct database access to configure channels
