# PaperSorter Example Configuration File
# Copy this file to your preferred location and update with your credentials
# Default location: ./config.yml

# Admin users configuration
# Users listed here will automatically receive admin privileges upon login
# Use email addresses for Google/GitHub OAuth or ORCID identifiers for ORCID
# Admin status is checked on each login and updated to match this list
admin_users:
  # Example email addresses for Google/GitHub OAuth
  # - "admin@example.com"
  # - "researcher@university.edu"
  # Example ORCID identifiers (must include @orcid.org suffix)
  # - "0000-0002-1825-0097@orcid.org"
  # - "0000-0003-4567-8901@orcid.org"

# Database configuration
db:
  type: postgres
  host: localhost
  port: 5432
  user: papersorter
  database: papersorter
  password: "your_database_password_here"

# Web interface configuration
web:
  # Base URL for web interface (used for "More Like This" links in notifications)
  base_url: "https://your-domain.example.com"
  # Flask secret key for session management
  # Generate with: python -c "import secrets; print(secrets.token_hex(32))"
  flask_secret_key: "generate_with_python_secrets.token_hex(32)"

# OAuth configuration for web interface authentication
# Configure one or both providers as needed
oauth:
  # Google OAuth configuration
  google:
    client_id: "your_google_oauth_client_id.apps.googleusercontent.com"
    secret: "your_google_oauth_client_secret"

  # GitHub OAuth configuration
  github:
    client_id: "your_github_oauth_client_id"
    secret: "your_github_oauth_client_secret"

  # ORCID OAuth configuration (essential for academic users)
  orcid:
    client_id: "your_orcid_oauth_client_id"
    secret: "your_orcid_client_secret"
    sandbox: false  # Set to true for testing with sandbox.orcid.org

# Embedding API configuration
# Supports OpenAI-compatible APIs (OpenAI, Solar LLM, Google Vertex AI via Gemini, etc.)
embedding_api:
  api_key: "your_api_key"
  # Optional: custom API endpoint (defaults to https://api.openai.com/v1)
  api_url: "https://api.openai.com/v1"
  # Optional: model name (defaults to text-embedding-3-large)
  model: "text-embedding-3-large"
  # Embedding dimensions
  dimensions: 3072

# Summarization API configuration
# Used for generating article summaries
summarization_api:
  api_key: "your_openai_api_key"
  # Optional: custom API endpoint (defaults to https://api.openai.com/v1)
  api_url: "https://api.openai.com/v1"
  # Optional: model name for summarization
  model: "gpt-4o-mini"

# Scholarly database configuration
# Choose between Semantic Scholar and OpenAlex for enriching article metadata
scholarly_database:
  # Provider to use: "semantic_scholar" or "openalex"
  provider: "semantic_scholar"

  # Date tolerance for automatic article matching during update task (in days)
  # When the update task tries to match RSS articles with scholarly database entries,
  # it will only consider articles published within this many days of the RSS date.
  # This does NOT affect web interface search functionality.
  # Default: 60
  match_date_tolerance_days: 60

  # Semantic Scholar configuration (if provider is semantic_scholar)
  semantic_scholar:
    api_key: "your_semanticscholar_api_key"
    # Optional: custom API URL
    # api_url: "https://api.semanticscholar.org/graph/v1/paper"
    # Optional: throttle between requests in seconds (default: 1)
    # throttle: 1

  # OpenAlex configuration (if provider is openalex)
  openalex:
    # OpenAlex requires a VALID email address for polite access (no API key needed)
    # Note: test@example.com and similar fake emails will NOT work
    email: "your_real_email@domain.com"
    # Optional: custom API URL
    # api_url: "https://api.openalex.org"
    # Optional: throttle between requests in seconds (default: 0.1)
    # throttle: 0.1

# SMTP configuration for email notifications
# Used when channel endpoint URLs start with "mailto:"
smtp:
  # SMTP server hostname
  host: "smtp.example.com"
  # SMTP server port (25 for plain, 587 for STARTTLS, 465 for SSL/TLS)
  port: 25
  # Enable STARTTLS (for port 587)
  use_tls: false
  # Enable SSL/TLS (for port 465)
  use_ssl: false
  # Connection timeout in seconds
  timeout: 30
  # Note: Authentication support will be added in a future version

# Email notification configuration
email:
  # Sender email address
  from_address: "papersorter@example.com"
  # Sender display name
  from_name: "PaperSorter Newsletter"
  # Email subject template (Python f-string format, can use {date} variable)
  subject_template: "Research Papers Digest - {date:%Y-%m-%d}"

# Storage configuration
storage:
  # Directory for storing AI-generated poster images
  ai_poster_dir: "./ai_posters"

# Note: Channel endpoints are configured per channel in the database
# Use the web interface or direct database access to configure channels
# The system auto-detects notification type based on the endpoint URL:
#   - mailto:user@example.com -> Email notifications (batched newsletter)
#   - https://hooks.slack.com/... -> Slack notifications (individual messages)
#   - https://discord.com/api/webhooks/... -> Discord notifications (individual embeds)
